JVM_0.1 {
  global :
    SysTraceFile;
    SysErrorFile;
    JavaArgc;
    JavaArgs;
    Me;
    bootRecord;
    verbose;
    bootCodeFilename;
    bootDataFilename;
    bootRMapFilename;
    initialHeapSize;
    maximumHeapSize;
    verboseBoot;
    sysJavaVM;
    findMappable;
    parse_memory_size;
    sysInitialize;
    sysMalloc;
    sysExit;
    JNI_GetDefaultJavaVMInitArgs;
    JNI_CreateJavaVM;
    JNI_GetCreatedJavaVMs;
  local : *;
};
